P.when("A","jQuery").register("VideoAdsLightboxMobile",function(A,$){var FETCH_CONTENT_TIMEOUT_DURATION_MILLIS=5000;
var MOBILE_LIGHTBOXES={};
var MobileLightbox=function(config){this._contentEndpoint=config.contentEndpoint;
this._itemConfig=config.itemConfig;
this._popoverId=config.popoverId;
this._popoverName=config.popoverName;
this._isPopoverContentsSet=false;
this._itemMetadatas=[];
this._contentState=null;
this._playRequestTimestamp=null;
};
MobileLightbox.prototype={bind:function(eventName,callback,scope){if(!eventName||!callback){return this;
}this._events=this._events||{};
var callbacks=this._events[eventName]||[];
callbacks.push({type:eventName,callback:callback,scope:scope||this});
this._events[eventName]=callbacks;
return this;
},trigger:function(eventName,eventContext){if(!this._events){return this;
}$.each(this._events[eventName]||[],function(key,eventObj){eventObj.callback.call(eventObj.scope,eventObj.type,eventContext);
});
return this;
},addItemMetadata:function(metadata){this._itemMetadatas.push(metadata);
},loadAndSetContent:function(success,error){success=success||$.noop;
error=error||$.noop;
var that=this;
$.ajax({timeout:FETCH_CONTENT_TIMEOUT_DURATION_MILLIS,url:this._contentEndpoint}).done(function(contentsHtml){var $popover=$("#"+that._popoverId);
if(!$popover.length){A.on("a:popover:beforeShow:"+this._popoverName,function(){that._setPopoverContents(contentsHtml);
success();
});
}else{that._setPopoverContents(contentsHtml);
success();
}}).fail(function(){console.error("Failed to retrieve mobile lightbox content");
error();
});
},recordPlayRequestTimestamp:function(timestamp){this._playRequestTimestamp=timestamp;
},getPlayRequestTimestamp:function(){return this._playRequestTimestamp;
},getContentState:function(){return this._contentState;
},updateContentState:function(state){this._contentState=state;
this.trigger("stateupdated",state);
return this;
},_setPopoverContents:function(contentsHtml){if(this._isPopoverContentsSet){return;
}var $popover=$("#"+this._popoverId).removeClass("a-popover-loading").html(contentsHtml);
this._applyItemMetadataAndSetContentState($popover);
this._enableHiResImages($popover);
this._isPopoverContentsSet=true;
},_applyItemMetadataAndSetContentState:function($popover){var itemConfig=this._itemConfig;
var metadatas=this._itemMetadatas;
var loadMediaContexts={};
var $items=$popover.find("."+itemConfig.itemsClassName);
$items.each(function(index,item){if(index>metadatas.length){return;
}var $product=$(item);
var metadata=metadatas[index];
$product.find("."+itemConfig.imageClassName).css("background-image",'url("'+metadata.imageUrl+'")');
$product.find("."+itemConfig.titleClassName).html(metadata.shortContentTitle);
$product.find("."+itemConfig.durationClassName).html(metadata.formattedDuration);
var anchorId=$product.find("a").click(function(){return false;
}).attr("id");
loadMediaContexts[anchorId]={contentId:metadata.asin,contentTitle:metadata.contentTitle,index:index,shortContentTitle:metadata.shortContentTitle};
});
var firstItemId=$items.first().find("a").addClass("airy-selected").attr("id");
this._contentState={curLoadMediaContext:loadMediaContexts[firstItemId],loadMediaContexts:loadMediaContexts};
},_enableHiResImages:function($popover){var metadatas=this._itemMetadatas;
var itemConfig=this._itemConfig;
var hiResImageMarker=itemConfig.hiResImageMarker;
if(!hiResImageMarker){return;
}P.when(hiResImageMarker).execute(function(){$popover.find("."+itemConfig.imageClassName).each(function(index){var metadata=metadatas[index];
if(!metadata.hiResImageUrl){return;
}$(this).css("background-image",'url("'+metadata.hiResImageUrl+'")');
});
});
}};
return{create:function(lightboxConfig){var lightbox=new MobileLightbox(lightboxConfig);
MOBILE_LIGHTBOXES[lightboxConfig.popoverName]=lightbox;
return lightbox;
},get:function(popoverName){return MOBILE_LIGHTBOXES[popoverName];
}};
});
